replicaCount: 1
revisionHistoryLimit: 0
deploymentStrategy:
  type: RollingUpdate

## PodDisruptionBudget
## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget
# maxUnavailable: 1

image:
  repository: snipe/snipe-it
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v8.3.1"

service:
  type: ClusterIP
  annotations: {}

config:
  mariadb:
  ## All of these values are only used when mysql.enabled is set to false
    externalDatabase: {}
      # user: "snipe-it"
      # pass: "pass"
      # name: snipeit-db
      # host: snipeit-mariadb
      # port: 3306

  snipeit:
    env: production
    debug: false
    url: https://snipeit.homelab.com
    key: "base64:l42tajVREklFSB6GoBdRSa8772oc911TM41JIL7QSM4="
    timezone: Europe/Prague
    locale: en
    envConfig: 
      #mail configuration   
      # MAIL_MAILER: smtp
      # MAIL_HOST: 
      # MAIL_PORT: 25
      # MAIL_ENCRYPTION: null
      # MAIL_FROM_ADDR:
      # MAIL_FROM_NAME: 
      # MAIL_REPLYTO_ADDR: 
      # MAIL_REPLYTO_NAME: 
      # MAIL_AUTO_EMBED: true
      # MAIL_AUTO_EMBED_METHOD: base64
      # MAIL_TLS_VERIFY_PEER: false
       #log configuration
       LOG: daily
       APP_LOG_MAX_FILES: 7
       LOG_LEVEL: debug
       LOG_CHANNEL: stack

  externalSecrets: ""

mariadb:
  ## Whether to deploy a mysql server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
  enabled: true
  ## Create a database and a database user
  ##
  auth:
    enabled: true
    existingSecret: ""
    username: snipeit
    database: snipeit-db
    password: asdljhafljhas769SADaighnks87394gfsdfkajdsds

  persistence:
    enabled: true
    accessModes: 
      - ReadWriteOnce
    size: 8Gi

persistence:
  enabled: true
  annotations: {}
  accessMode: ReadWriteOnce
  existingClaim: ""
  size: 4Gi

  www:
    mountPath: /var/lib/snipeit
    subPath: www
  sessions:
    mountPath: /var/www/html/storage/framework/sessions
    subPath: sessions
     

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  pathType: ImplementationSpecific
  hosts:
    - snipeit.homelab.com
  # tls: 
  #  - secretName: wildcard-ttcdev-bisim-cloud-key
  #    hosts:
  #      - snipeit.ttcdev.bisim.cloud


# resources:
   
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

extraAnnotations: {}
  # Extra Annotations that will be added to the SnipeIT Pod(s)
  # app.kubernetes.io/instance: snipeit
extraManifests: []

# extraVolumeMounts: 
#   - mountPath: /etc/ssl/certs/
#     name: trust-chain
#     readOnly: true
# extraVolumes: 
#   - configMap:
#       name: global-bisimulations-com
#     name: trust-chain
 
 

