kind: Secret
apiVersion: v1
metadata:
  name: {{ include "snipeit.fullname" . }}
  labels:
    {{ include "snipeit.labels" . | indent 4 | trim }}
data:
  
{{ if not .Values.config.externalSecrets }}
{{- if .Values.mariadb.enabled }}
  MYSQL_USER: {{ .Values.mariadb.auth.username | b64enc }}
  MYSQL_DATABASE: {{ .Values.mariadb.auth.database | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mariadb.auth.password | b64enc }}
  MYSQL_PORT_3306_TCP_ADDR: {{ include "snipeit.mariadbFullname" . | b64enc }}
  MYSQL_PORT_3306_TCP_PORT: {{ "3306" | b64enc }}
  APP_KEY: {{ .Values.config.snipeit.key | b64enc }}
{{- else }}
  MYSQL_USER: {{ .Values.config.mariadb.externalDatabase.user | b64enc }}
  MYSQL_DATABASE: {{ .Values.config.mariadb.externalDatabase.name | b64enc }}
  MYSQL_PASSWORD: {{ .Values.config.mariadb.externalDatabase.pass | b64enc }}
  MYSQL_PORT_3306_TCP_ADDR: {{ .Values.config.mariadb.externalDatabase.host | b64enc }}
  MYSQL_PORT_3306_TCP_PORT: {{ .Values.config.mariadb.externalDatabase.port | quote | b64enc }}
  APP_KEY: {{ .Values.config.snipeit.key | b64enc }}
{{- end }}
{{- end }}
{{ range $key, $value := .Values.config.snipeit.envConfig }}
  {{ $key }}: {{ $value | toString | b64enc }}
{{- end}}
