#self-sign cert creted with selfsigned issuer
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-ca-crt
  namespace: cert-manager
spec:
  isCA: true
  commonName: homelab-ca
  secretName: homelab-ca-secret
  duration: 87600h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer