apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-services
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/zelinar/Helm_Charts
        revision: master
        directories:
          - path: core-services/*/
  template:
    metadata:
      name: '{{.path.basename}}-core'
      annotations:
        #argocd.argoproj.io/manifest-generate-paths: .
        # use syncvawe to order workload deployment
        argocd.argoproj.io/sync-wave: >-
          {{- if eq .path.basename "metallb" -}}-10
          {{- else if eq .path.basename "cert-manager" -}}-5
          {{- elif eq .path.basename "metallb-custom-ip-pool" -}}8
          {{- else if eq .path.basename "traefik" -}}0
          {{- else if eq .path.basename "longhorn" -}}5
          {{- else if eq .path.basename "cnpg-operator" -}}10
          {{- else if eq .path.basename "homelab-tls" -}}10
          {{- else -}}0
          {{- end }}
    spec:
      project: core-services
      source:
        repoURL: https://github.com/zelinar/Helm_Charts
        targetRevision: master
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true        