apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-services
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - git:
        repoURL: https://github.com/zelinar/Helm_Charts
        revision: master
        directories:
          - path: core_services/*
  template:
    metadata:
      name: '{{ .path.basename }}'
    spec:
      project: core-services
      source:
        repoURL: https://github.com/zelinar/Helm_Charts
        targetRevision: master
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: >-
          {{- $name := .path.basename -}}
          {{- if eq $name "longhorn" -}}
            longhorn-system
          {{- else if eq $name "metallb" -}}
            metallb-system
          {{- else if eq $name "traefik" -}}
            traefik
          {{- else if eq $name "cert-manager" -}}
            cert-manager
          {{- else if eq $name "cnpg-operator" -}}
            cnpg-system
          {{- else if eq $name "homelab-tls" -}}
            cert-manager
          {{- else -}}
            {{ $name }}
          {{- end -}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - ServerSideApply=true