apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core-services
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  sourceRepos:
    - https://github.com/zelinar/Helm_Charts

  clusterResourceWhitelist:
    - group: '*'
      kind: '*' 

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'    

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc