# Default values for argocd.
argocd:
  

  # redis-ha:
  #   enabled: true

  # controller:
  #   replicas: 1

    server:
      autoscaling:
        enabled: true
        minReplicas: 2

      extraArgs:
       - --insecure   
      
    service:
      type: ClusterIP

    

  # repoServer:
  #   autoscaling:
  #     enabled: true
  #     minReplicas: 2  

  # applicationSet:
  #   replicas: 2     
  

  
    

