# Default values for argocd.
argo-cd:
  redis-ha:
    enabled: true

  controller:
    replicas: 1

  global:
    domain: argocd-dev.homelab.cloud

  server:
    autoscaling:
      enabled: true
      minReplicas: 2 
    ingress:
      enabled: true
      ingressClassName: traefik
      controller: generic
      extraTls:
        - hosts:
          - argocd-dev.homelab.cloud
    resources:      
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 192Mi
    
  configs:
    params:
      # TLS Termination at Ingress (internal TLS off)
      server.insecure: true
    autoscaling:
      enabled: true
      minReplicas: 2
    
  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 2
    resources:
      limits:
        cpu: 800m
        memory: 768Mi
      requests:
        cpu: 200m
        memory: 512Mi  

  applicationSet:
    replicas: 1
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi




