# Default values for argocd.
argo-cd:
  redis-ha:
    enabled: true

  controller:
    replicas: 1

  global:
    domain: argocd-mngmt.homelab.com

  server:
    autoscaling:
      enabled: true
      minReplicas: 2 
    ingress:
      enabled: true
      ingressClassName: traefik
      controller: generic
    extraTls:
      - hosts:
          - argocd-mngmt.homelab.com
    
  configs:
    params:
      # TLS Termination at Ingress
      server.insecure: true
    autoscaling:
      enabled: true
      minReplicas: 2
    
  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 2

  applicationSet:
    replicas: 2





