apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/zelinar/Helm_Charts
    path: core_services/cnpg-operator
    targetRevision: master
    helm:
      dependencyUpdate: true
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations      
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  