apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgbouncer
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/zelinar/Helm_Charts
    path: core_services/pgbouncer
    targetRevision: master
    helm:
      dependencyUpdate: true
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
  # ignore differences in CRD annotations during drift detection and sync !TODO! - deploy CRDs in separate step    
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations      
  destination:
    namespace: pgbouncer
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 