apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/zelinar/Helm_Charts
    path: core_services/traefik
    targetRevision: master
    helm:
      dependencyUpdate: true
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 